services:
    pwg.UserAvatars.listener:
        class: pwg\UserAvatars\event\listener
        arguments:
            - @user
            - @path_helper
            - @dbal.conn
        tags:
            - { name: event.listener }
